version: '3.6'

volumes:
  postgres_data:
    name: prod_movies_data
  static_volume:
    name: prod_static

networks:
  movies_network:
    driver: bridge

services:

  postgres:
    build:
      context: .
      dockerfile: ./Docker-settings/postgres/Dockerfile
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - movies_network

  movies_web:
    build:
      context: .
      dockerfile: Docker-settings/web_django/Dockerfile
    container_name: movies_web
    restart: always
    volumes:
      - static_volume:/code/movies_admin/static
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - movies_network

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    restart: always
    volumes:
      - static_volume:/code/movies_admin/static
      - ./Docker-settings/nginx/src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Docker-settings/nginx/src/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
    depends_on:
      - movies_web
    networks:
      - movies_network
