version: "3.6"

volumes:
  elastic_data:
    name: elastic_data


services:
  elasticsearch:
    image: elasticsearch:7.13.2
    container_name: elasticsearch
    #restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: kibana:7.13.4
    container_name: kibana_dev
    ports:
      - "5601:5601"
    env_file:
      - .env
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge